services:
  pb:
    image: pocketbase.io:${PB_VERSION:-0.22.13}
    build:
      context: ./.docker/pocketbase/
      args:
        - PB_VERSION:${PB_VERSION:-0.22.13}
    container_name: pb
    ports:
      - "${PB_HTTP_PORT:-8080}:8080"
    volumes:
      - ./pb/pb_data:/pb/pb_data
#      - ./pb/pb_hooks:/pb/pb_hooks
  nuxtjs:
    build:
      context: ./src/nuxtui-pg
      dockerfile: ../../.docker/node/Dockerfile
    environment:
      - NODE_ENV=production
      - NUXT_PB_API=http://pb:8080
      - NUXT_PB_USER=<required-adminuser>
      - NUXT_PB_PASS=<required-adminpw>
      - NUXT_PUBLIC_PB_API=http://localhost:8080
      - NUXT_FD_AUTH_TOKEN=
    container_name: nuxtjs
    ports:
      - "3000:3000"
    command: ["node", ".output/server/index.mjs"]